# Generated by Django 4.1.6 on 2023-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("certificate", models.ImageField(upload_to="./shopping/certificate/")),
                ("verified", models.BooleanField(default=False)),
            ],
        ),
    ]
