# Generated by Django 4.1.6 on 2023-03-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("selling", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Seller",),
    ]
