# Generated by Django 4.1.6 on 2023-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="./shopping/no_image.jpg", upload_to="./shopping/"
            ),
        ),
    ]
