# Generated by Django 4.1.6 on 2023-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="./shopping/no_image.jpg", upload_to=""),
        ),
    ]
